//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorLocalization.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorLocalization.Server.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGLISH.
        /// </summary>
        public static string _000 {
            get {
                return ResourceManager.GetString("000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near a great forest there lived a poor woodcutter and his wife,.
        /// </summary>
        public static string _001 {
            get {
                return ResourceManager.GetString("001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and his two children; the boy&apos;s name was Hansel and the girl&apos;s Grethel..
        /// </summary>
        public static string _002 {
            get {
                return ResourceManager.GetString("002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They had very little to bite or to sup, and once, when there was great dearth in the land,.
        /// </summary>
        public static string _003 {
            get {
                return ResourceManager.GetString("003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the man could not even gain the daily bread..
        /// </summary>
        public static string _004 {
            get {
                return ResourceManager.GetString("004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As he lay in bed one night thinking of this,.
        /// </summary>
        public static string _005 {
            get {
                return ResourceManager.GetString("005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and turning and tossing, he sighed heavily, and said to his wife,.
        /// </summary>
        public static string _006 {
            get {
                return ResourceManager.GetString("006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;What will become of us? we cannot even feed our children; there is nothing left for ourselves.&quot;.
        /// </summary>
        public static string _007 {
            get {
                return ResourceManager.GetString("007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;I will tell you what, husband,&quot; answered the wife;.
        /// </summary>
        public static string _008 {
            get {
                return ResourceManager.GetString("008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;we will take the children early in the morning into the forest, where it is thickest; .
        /// </summary>
        public static string _009 {
            get {
                return ResourceManager.GetString("009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we will make them a fire, and we will give each of them a piece of bread, then we will go to our work and leave them alone; they will never find the way home again, and we shall be quit of them.&quot;.
        /// </summary>
        public static string _010 {
            get {
                return ResourceManager.GetString("010", resourceCulture);
            }
        }
    }
}
